### ISSUE TITLE
A picture of a persona in persona page and maybe a css framework for a nicer ui

### ISSUE THREAD

**Issue by Ley21** [chinhodado/persona5_calculator#2]
Hi,

it would be nice if you could add images of the persona, if there any exists.
And it will also be nice if you can use a css framework like bootstrap to let the page look a little nicer.

**Comment by vlxs** [comment]
If it helps, I added support for [Semantic UI](https://semantic-ui.com/) and improved the site's layout on mobile devices (as that's mostly how I use the site) on my local copy ([fork here](https://github.com/vlxs/persona5_calculator)). I can open a pull request if you'd like (not sure if you're interested in changing the UI in the first place).

**Comment by chinhodado** [comment]
@vlxs That's great! You can make a PR and I'll merge it.
