### ISSUE TITLE
Incorrect Skill Descriptions

### ISSUE THREAD

**Issue by TubePowered** [chinhodado/persona5_calculator#22]
Hey, I just wanted to mention that a number of the skill descriptions are incorrect and that you might want to go refresh your database since I know that in at least a couple of skills' cases, Aqiu384's "**full_skills.js**" has since been updated to fix a number of the errors. I actually noticed that Angelic Grace was incorrect about a week and a half ago and—knowing that you utilized Aqiu's code—actually confirmed their .js as the source of the error and mentioned it to them, prompting a fix of it as well as numerous other things (I haven't gone through all of the things that got fixed, I just know that a few have been fixed alongside Angelic Grace); I'll include the revision's link that I was given at the bottom of this post. 

I'm brand-spanking new to GitHub and quite honestly know just the tiniest bit more than nothing about how it all works. I honestly only joined to bring attention to the skill description errors and because I planned on learning how to start my own project... So I honestly don't know how this all works. I'm kind of just assuming that your calculator pulls information directly from Aqiu's databases as credited in your ReadMe, but the fact that the recently-fixed skill description(s) have yet to reflect any changes really threw me off. I'm basically typing this out both in the hopes that a fix is as easy as hitting a refresh button—so to speak—regarding any info pulled from that database as well as with the intention of being at least _somewhat_ helpful. Otherwise, I've just wasted your time even more than my awfully tedious and drawn-out writing style likely already has, as is wont to do. 

If you only used their databases as reference and instead need to take a more manual approach to updating your info, let me know via message or something and I would be more than happy to make note of all the incorrect skills as well as what needs to be changed with them in my free time! A lot of people use your calculator and I'm sure most of them only silently appreciate what you have and are doing here. If I can help to show my gratitude through something as simple as this, then I would gladly do so. You've saved myself, and many of my friends a lot of time, headaches, and frustration!

### ...necessary tl;dr ↴
Aqiu384's "**full_skills.js**" that you referenced in your ReadMe had some skill errors, namely with Angelic Grace, which has since been fixed on their end along with a number of other skills that can be seen in the link at the bottom. I brought the description errors up to them after seeing an identical error in said file which is how I know that they fixed some errors as well as that the calculator doesn't yet reflect them. Message me if you want help from me in fixing any other, similar errors.

revision linked to me by aqiu384: [https://github.com/aqiu384/aqiu384.github.io/commit/948f294d3deac29d65eab1ac374100411eecf9c0](url)

**Comment by chinhodado** [comment]
I will fix this when I have time, or you can also send a pull request.

**Comment by chinhodado** [comment]
Fixed
