### ISSUE TITLE
Recipe to fuse Satan.

### ISSUE THREAD

**Issue by DuIslingr** [chinhodado/persona5_calculator#27]
So I was having an issue with this, since none of the specified fusions to create him were working for me, I googled about it and came across some threads with people having the same issue. Now I don't know exactly why but I think it might have to do with leveling messiah Picaro past its initial level value. As mine was level 99 and it wasnt working. SO what ended up working for me was fusing Messiah Picaro with Regent. but it looks like Koh-i-Noor is an option as well. I dont have the final treasure demon in the list to test though.

https://i.imgur.com/2Fo0mUw.jpg

**Comment by dsuurlant** [comment]
I've been able to fuse Satan using Ongyo-Ki and Yoshitsune.
