### ISSUE TITLE
Black Frost fusion recipe incomplete

### ISSUE THREAD

**Issue by twilightL** [chinhodado/persona5_calculator#28]
Your fusion recipe for Black Frost says King Frost + Jack Frost, but you need Jack-o'-Lantern as well.

**Comment by Kyleo91** [comment]
The data is included, but there is a typo in the name of Jack-o’-lantern (it’s missing both hyphens) therefore is being missed.

**Comment by chinhodado** [comment]
Thanks, I fixed it.
