### ISSUE TITLE
Fusion recipes for Kin-Ki are incorrect

### ISSUE THREAD

**Issue by Jmacek** [chinhodado/persona5_calculator#4]
The two cheapest ones product Ara Mitima, not Kin-Ki. I haven't checked the others but I see that the same fusions are shown on Ara Mitima. 

Relevant fusions:
1
22,807 ¥
Shiki-Ouji (21 / Chariot)
Regent (10 / Emperor)
2
32,167 ¥
Shiki-Ouji (21 / Chariot)
Stone of Scone (20 / Fortune)

**Comment by chinhodado** [comment]
Shiki-Ouji (21 / Chariot) + Regent (10 / Emperor)

Note that Regent is a rare persona. Rare persona fusion depends on the current level of your persona, not the base level. For simplicity, the calculator uses the base level. So unless your Shiki-Ouji is exactly level 21, you may not get the same result. What is its level?

**Comment by Jmacek** [comment]
Ohh I bet that's what it was. I can pretty much guarantee that my Shiki-Ouji wasn't level 21 during fusion, since I have the +10 for Chariot. I didn't realize the persona level has an affect on the fusion result when fusing with a rare persona.

My mistake, you should clarify that somewhere when fusing with rare persona, it's not inherently obvious at first glance.

**Comment by chinhodado** [comment]
Added notice
