### ISSUE TITLE
please sort Arcana by the Arcana

### ISSUE THREAD

**Issue by Blackwolf291** [chinhodado/persona5_calculator#59]
Looking at who i'm missing, i used the arcana sort....and got really triggered by it being alphabetical, instead of following the arcana.

Some lists you do not sort alphabetically.
Friday, Monday, Saterday, Sunday, Thursday, Tuesday, Wednesday.
April, August, December, February, January, July, June, March, May, November, October, September.

Please consider sorting the Arcana in it's inherent order.

**Comment by aykrivwassup** [comment]
Agreed. It's how it appears in-game so it just makes sense.
