### ISSUE TITLE
Broken Stat Screen

### ISSUE THREAD

**Issue by oceanstuck** [chinhodado/persona5_calculator#60]
The stat screen for Asura seems to be broken on the Royal calculator, giving this error page:
![823F4831-2BE7-4E40-A556-03FD96100136](https://user-images.githubusercontent.com/56813824/103407567-fc0b6880-4b13-11eb-9251-0810e0de378c.png)

**Comment by alichaudry** [comment]
@oceanstuck this should no longer be an issue, PR #62 (issue #61) resolved it

**Comment by alichaudry** [comment]
@chinhodado we can close this issue
