### ISSUE TITLE
Asura/Asuro-Ou is broken on persona 5 royal calculator

### ISSUE THREAD

**Issue by MegaBloopy** [chinhodado/persona5_calculator#61]
https://chinhodado.github.io/persona5_calculator/indexRoyal.html#/persona/Asura
Gives wonky JS placeholders like {{persona.name}} and https://chinhodado.github.io/persona5_calculator/indexRoyal.html#/persona/Asura-Ou says not found

**Comment by alichaudry** [comment]
Agreed with @MegaBloopy, this is still broken. I'm not a JS expert but if someone can point me in the right direction I can take a stab at creating a PR to fix this.

**Comment by alichaudry** [comment]
For the sake of posterity, an image of what the broken Asura page for p5r looks like (as of right now):

![image](https://user-images.githubusercontent.com/15057353/105808322-7b565580-5f75-11eb-916c-522a5ff5b3e0.png)

**Comment by alichaudry** [comment]
#62 attempts to solve this problem

**Comment by alichaudry** [comment]
Asura on p5r is working [now](https://chinhodado.github.io/persona5_calculator/indexRoyal.html#/persona/Asura):
![image](https://user-images.githubusercontent.com/15057353/105885453-23503b00-5fd7-11eb-8e6a-50ad09338e19.png)


We can close this issue @chinhodado
