### ISSUE TITLE
Shiki-Ouji has incorrect stats

### ISSUE THREAD

**Issue by toancaro** [chinhodado/persona5_calculator#67]
[Shiki-Ouji](https://chinhodado.github.io/persona5_calculator/#/persona/Shiki-Ouji) has incorrect stats:

Current: 
Strength | Magic | Endurance | Agility | Luck
-- | -- | -- | -- | --
11 | 15 | 16 | 16 | 13

Correct:
Strength | Magic | Endurance | Agility | Luck
-- | -- | -- | -- | --
16 | 14 | 15 | 14 | 11

Source: https://megamitensei.fandom.com/wiki/Shiki-Ouji#Persona

**Comment by alichaudry** [comment]
@toancaro Want to take a stab at correcting that and creating a PR?

**Comment by Dimitridherr** [comment]
I created a PR to fix this
