### ISSUE TITLE
Feng Huang

### ISSUE THREAD

**Issue by Angely87** [chinhodado/persona5_calculator#9]
I think Feng Huang is called Phoenix in the english version of the game, I also noticed that the fusion of Phoenix (25) with Regent turns into an Unicorn instead of Anzu, while on the calculator it shows Anzu x regent = Unicorn (ig it's like that too) & no Phoenix x Regent. Please look into it, it could also be a bug in the game though. :s 

P.s Thank you for the calculator!

**Comment by chinhodado** [comment]
Thanks, I fixed Feng Huang -> Phoenix.

I don't quite follow the second part, but please remember that rare fusion depends on your persona's current level. 

Also note that 

 - given a rare persona X and a result persona Z, there can be multiple persona Y such that X + Y = Z (i.e. Y is not unique)

 - given a normal persona Y and a result persona Z, there can be multiple rare persona X such that X + Y = Z (i.e. X is not unique)

**Comment by Angely87** [comment]
I see, I meant to say that the Phoenix + Regent =Unicorn combo was not on the list of possibilties while it's possible it's the  result i had for my lvl 25 Phoenix +Regent, but it was not on the calculator fusion list which confused me & made me think it might've been a bug. 

P.s I get now that treasure persona's can give multiple results it's just that I didn't get the Phoenix + Regent =Anzu.:)
